# quality_checker.py
import json
import re
import os
import subprocess
import shutil
import networkx as nx
from typing import Tuple, Dict, Any, List

Model = Dict[str, Any]


def _sanitize_name(name: str) -> str:
    """清理名称，确保 NuSMV 兼容 (a-z, 0-9, _)"""
    if not isinstance(name, str):
        return str(name)

    name = name.strip()
    # 如果以数字开头，加前缀 n_
    if name and name[0].isdigit():
        name = "n_" + name

    sanitized = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    sanitized = sanitized.lower()
    return re.sub(r'_+', '_', sanitized).strip('_')


class QualityChecker:
    def __init__(self):
        # 检查 NuSMV 是否可用
        self.nusmv_executable = shutil.which("NuSMV")
        if not self.nusmv_executable:
            # 尝试常见路径
            if os.path.exists("/usr/bin/NuSMV"):
                self.nusmv_executable = "/usr/bin/NuSMV"
            elif os.path.exists("/usr/local/bin/NuSMV"):
                self.nusmv_executable = "/usr/local/bin/NuSMV"
            else:
                print("警告: 未在 PATH 中找到 'NuSMV' 可执行文件。")

    def check(self, model_json: str) -> Tuple[bool, str]:
        """
        双重验证流程:
        1. NetworkX: 结构完整性检查
        2. NuSMV: 形式化 CTL 检查 + 语法检查
        """
        print("[模块 3] 开始联合质量检查...")
        try:
            model = json.loads(model_json)
            # 过滤通配符状态，防止 NetworkX 报错
            if 'states' in model:
                model['states'] = [s for s in model['states'] if s != '*']
        except json.JSONDecodeError as e:
            return (False, f"JSON 格式无效: {e}")

        # === 阶段 1: NetworkX 结构检查 ===
        nx_passed, nx_reason = self._check_with_networkx(model)
        if not nx_passed:
            print(f"[模块 3] NetworkX 结构检查失败: {nx_reason}")
            return (False, nx_reason)

        print("[模块 3] NetworkX 结构检查通过。正在进行 NuSMV 验证...")

        # === 阶段 2: NuSMV 形式化验证 ===
        if self.nusmv_executable:
            smv_passed, smv_reason = self._check_with_nusmv_binary(model)
            if not smv_passed:
                print(f"[模块 3] NuSMV 验证失败: {smv_reason}")
                return (False, smv_reason)
            print("[模块 3] NuSMV 验证通过。")
        else:
            print("[模块 3] 警告: 未找到 NuSMV，跳过阶段 2。")
            return (True, "NetworkX 检查通过 (NuSMV 已跳过)。")

        return (True, "通过所有质量检查。")

    def save_smv_file(self, model_json: str, filename: str):
        """保存最终验证通过的模型"""
        try:
            model = json.loads(model_json)
            # 1. 生成代码
            smv_content = self._convert_json_to_smv(model)

            # 2. 生成属性 (使用修正后的方法名)
            specs = self._get_ctlspec_strings(model)

            # 拼接属性
            smv_content += "\n-- ==================================================\n"
            smv_content += "-- 验证属性 (基于 EnviRE 2024 论文)\n"
            smv_content += "-- ==================================================\n"

            for name, spec in specs:
                smv_content += f"\n-- {name}\nCTLSPEC {spec}\n"

            init_state = _sanitize_name(model.get('init_state', 'unknown'))
            header = f"-- SMV Model generated by DeepSeek & QualityChecker\n"
            header += f"-- Initial State: {init_state}\n\n"

            with open(filename, "w", encoding="utf-8") as f:
                f.write(header + smv_content)
            print(f"[模块 3] 最终 SMV 模型已保存至: {filename}")
        except Exception as e:
            print(f"[模块 3] 保存 SMV 文件出错: {e}")

    def save_debug_smv(self, model_json: str, filename: str):
        """调试用保存"""
        try:
            model = json.loads(model_json)
            smv_content = self._convert_json_to_smv(model)
            specs = self._get_ctlspec_strings(model)

            init_state = _sanitize_name(model.get('init_state', 'unknown'))
            header = f"-- SMV DEBUG Model\n-- Initial State: {init_state}\n\n"

            for name, spec in specs:
                smv_content += f"\n-- {name}\nCTLSPEC {spec}\n"

            with open(filename, "w", encoding="utf-8") as f:
                f.write(header + smv_content)
        except Exception:
            pass

    # ---------------------------------------------------------
    # 核心辅助函数 (关键修复部分)
    # ---------------------------------------------------------
    def _get_ctlspec_strings(self, model: Model) -> List[Tuple[str, str]]:
        """
        生成 CTL 属性列表 (严格遵循论文 AG ((...) & (...)) 格式)。

        修改点：
        1. [转换完备性 (Transition Completeness/Validity)]:
           将所有状态的跳转约束合并为一条 AG 全局公式。
           公式：AG ( (s1 -> AX(next_s1)) & (s2 -> AX(next_s2)) & ... )

        2. [可重置性 (Resettability)]:
           保持 AG (EF (state = init))。
        """
        specs = []
        # 1. 获取并排序所有状态
        states = sorted([_sanitize_name(s) for s in model['states'] if s != '*'])
        init_s = _sanitize_name(model.get('init_state', states[0] if states else 'standby'))

        # 2. 构建邻接表
        transition_map = {s: set() for s in states}
        for t in model['transitions']:
            src = _sanitize_name(t['from'])
            dst = _sanitize_name(t['to'])
            if src == '*':
                for s in states: transition_map[s].add(dst)
            elif src in transition_map:
                transition_map[src].add(dst)

        # === 核心修改：构建单条全局完备性公式 ===
        validity_clauses = []

        for s in states:
            valid_next_states = list(transition_map[s])

            # 构造子句： (state = s -> AX (...))
            if not valid_next_states:
                # 如果无出边，默认为自环 (state = s)
                target_expr = f"state = {s}"
            else:
                # 构造目标集合: state = t1 | state = t2
                target_expr = " | ".join([f"state = {target}" for target in valid_next_states])

            # 添加子句
            # 逻辑：如果当前是状态 s，则下一步必须是 target_expr 中的一个
            clause = f"(state = {s} -> AX ({target_expr}))"
            validity_clauses.append(clause)

        # 3. 使用 '&' 拼接所有子句，并包裹在 AG 中
        if validity_clauses:
            # Join all clauses with " & "
            full_body = " & ".join(validity_clauses)
            # Wrap in AG
            global_formula = f"AG ({full_body})"

            # 添加到属性列表
            specs.append(("Transition_Validity_Global", global_formula))

        # === 4. 可重置性 (保持不变) ===
        specs.append(("Resettability", f"AG (EF (state = {init_s}))"))

        # === 5. (可选) 连通性 (Connectivity) ===
        # 论文标题虽然叫 Connectivity，但公式是结构检查。
        # 如果你还需要验证“从初始状态可达性”，建议额外保留 EF 检查：
        for s in states:
            if s != init_s:
                specs.append((f"Reachability_of_{s}", f"EF (state = {s})"))

        return specs

    def _convert_json_to_smv(self, model: Model) -> str:
        """
        JSON -> SMV 代码转换器
        特点：总是生成 Output 逻辑，确保 check 阶段能发现 Output 的语法错误。
        """
        states = sorted([_sanitize_name(s) for s in model['states'] if s != '*'])

        # 收集所有非空输入
        raw_inputs = set(_sanitize_name(t['input']) for t in model['transitions'])
        inputs = sorted([i for i in raw_inputs if i and i.strip() != ""])

        # 收集输出
        outputs = sorted(list(set(_sanitize_name(t.get('output', 'none')) for t in model['transitions'])))
        init_state = _sanitize_name(model.get('init_state', states[0] if states else 'standby'))

        # 生成 VAR
        smv = "MODULE main\nVAR\n"
        smv += f"  state : {{{', '.join(states)}}};\n"

        # 修复：防止生成空的 ": boolean;"
        for inp in inputs:
            smv += f"  {inp} : boolean;\n"

        if outputs:
            smv += f"  output : {{{', '.join(outputs)}}};\n"

        # 生成 ASSIGN
        smv += "ASSIGN\n"
        smv += f"  init(state) := {init_state};\n"
        smv += "  next(state) := case\n"

        for t in model['transitions']:
            s_from = _sanitize_name(t['from'])
            s_to = _sanitize_name(t['to'])
            s_in = _sanitize_name(t['input'])

            # 跳过空输入
            if not s_in or s_in not in inputs: continue

            cond_parts = [f"{i}" if i == s_in else f"!{i}" for i in inputs]
            cond_str = " & ".join(cond_parts)

            # 通配符处理
            if t['from'] == '*' or s_from == '' or s_from == '*':
                smv += f"    {cond_str} : {s_to};\n"
            else:
                smv += f"    state = {s_from} & {cond_str} : {s_to};\n"

        smv += "    TRUE : state;\n  esac;\n"

        # 生成 Output (总是生成，以便验证)
        if outputs:
            smv += "  output := case\n"
            for t in model['transitions']:
                s_from = _sanitize_name(t['from'])
                s_out = _sanitize_name(t.get('output', 'none'))
                s_in = _sanitize_name(t['input'])

                if not s_in or s_in not in inputs: continue

                cond_parts = [f"{i}" if i == s_in else f"!{i}" for i in inputs]
                cond_str = " & ".join(cond_parts)

                # 修复通配符 Output 生成
                if t['from'] == '*' or s_from == '' or s_from == '*':
                    smv += f"    {cond_str} : {s_out};\n"
                else:
                    smv += f"    state = {s_from} & {cond_str} : {s_out};\n"

            default_out = outputs[0] if outputs else 'none'
            smv += f"    TRUE : {default_out};\n  esac;\n"

        return smv

    # ---------------------------------------------------------
    # 阶段 1: NetworkX 检查
    # ---------------------------------------------------------
    def _check_with_networkx(self, model: Model) -> Tuple[bool, str]:

        try:

            G = nx.DiGraph()

            if 'states' not in model: return (False, "模型缺失 'states' 字段。")



            all_states = set([_sanitize_name(s) for s in model['states'] if s != '*'])

            # 1. Establish a set of alphabets (统计字母表/所有可能的输入)

            alphabet = set()

            for t in model['transitions']:

                inp = _sanitize_name(t['input'])

                if inp: alphabet.add(inp)



            init_state = _sanitize_name(model.get('init_state', list(all_states)[0] if all_states else ''))



            # 用于确定性检查的哈希表

            seen_transitions = {}



            # 用于清晰性检查的映射: state -> handled_inputs

            state_input_map = {s: set() for s in all_states}



            transitions = model.get('transitions', [])



            # === 遍历所有转换 (Traverse all transitions) ===

            for t in transitions:

                src = _sanitize_name(t['from'])

                dst = _sanitize_name(t['to'])

                inp = _sanitize_name(t['input'])

                out = _sanitize_name(t.get('output', 'none'))



                # [检查 1: Determinism / 确定性]

                if src != '*':

                    key = (src, inp)

                    val = (dst, out)

                    if key in seen_transitions:

                        prev_val = seen_transitions[key]

                        if prev_val != val:

                            return (False,

                                    f"确定性错误 (Determinism): 状态 '{src}' 在输入 '{inp}' 下行为冲突: {prev_val} vs {val}")

                    else:

                        seen_transitions[key] = val



                # [数据收集: Clarity / 清晰性]

                # 记录每个状态处理了哪些输入

                if src == '*':

                    # 通配符意味着所有状态都处理了这个输入

                    for s in all_states:

                        state_input_map[s].add(inp)

                elif src in all_states:

                    state_input_map[src].add(inp)



            # === [检查 2: Clarity / 清晰性 (完备性)] ===

            # "For each state, see if it can generate transitions for all input signals"

            for s in all_states:

                handled = state_input_map[s]

                # 计算未使用的输入信号 (Alphabet - Handled)

                missing = alphabet - handled



                if missing:

                    # 将集合转为列表并排序，方便阅读

                    missing_list = sorted(list(missing))

                    return (False,

                            f"清晰性错误 (Clarity): 状态 '{s}' 不完备。\n"

                            f"它没有定义对以下输入信号的响应: {missing_list}。\n"

                            f"根据 Mealy 机清晰性定义，每个状态必须处理所有可能的输入。")



            # (可选) 保留之前的孤立点检查作为额外的结构检查 Check #3

            # 虽然论文这段没提，但这在工程上很有用，建议保留

            # ...



            return (True, "NetworkX 检查通过 (符合 Determinism 和 Clarity 定义)。")



        except Exception as e:

            return (False, f"NetworkX 内部逻辑错误: {e}")

    # ---------------------------------------------------------
    # 阶段 2: NuSMV 检查
    # ---------------------------------------------------------
    def _check_with_nusmv_binary(self, model: Model) -> Tuple[bool, str]:
        temp_filename = "temp_verification.smv"
        try:
            # 1. 生成完整 SMV 内容
            smv_content = self._convert_json_to_smv(model)

            # 2. 调用 helper 函数生成属性列表
            specs = self._get_ctlspec_strings(model)

            for name, spec in specs:
                smv_content += f"\n-- {name}\nCTLSPEC {spec}\n"

            with open(temp_filename, "w") as f:
                f.write(smv_content)

            # 3. 运行 NuSMV (同时捕获 stdout 和 stderr)
            result = subprocess.run(
                [self.nusmv_executable, temp_filename],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,  # 关键：确保捕获错误流
                universal_newlines=True,
                timeout=10
            )

            # 4. 合并输出以捕获错误
            full_output = result.stdout + "\n" + result.stderr
            lower_output = full_output.lower()

            # 语法错误检查 (检查 returncode 和 关键词)
            if result.returncode != 0 or "syntax error" in lower_output or "parser error" in lower_output or "ambiguous" in lower_output:
                return (False, f"NuSMV 代码语法/编译错误:\n{full_output}")

            # CTL 属性检查
            if "is false" in result.stdout:
                return (False, self._parse_nusmv_output(result.stdout))

            return (True, "NuSMV 检查通过")

        except subprocess.TimeoutExpired:
            return (False, "NuSMV 验证超时。")
        except Exception as e:
            return (False, f"NuSMV 执行失败: {e}")
        finally:
            if os.path.exists(temp_filename):
                os.remove(temp_filename)

    def _parse_nusmv_output(self, output: str) -> str:
        lines = output.split('\n')
        failure_msg = "NuSMV 验证失败。\n"
        capturing_trace = False
        trace_lines = []

        for line in lines:
            if "specification" in line and "is false" in line:
                failure_msg += f"违反属性: {line.strip()}\n"
                capturing_trace = True
            elif "specification" in line and "is true" in line:
                capturing_trace = False
            elif capturing_trace:
                if "-> State" in line or "=" in line:
                    trace_lines.append(line.strip())

        if trace_lines:
            return failure_msg + "反例路径: " + " ".join(trace_lines)
        return failure_msg